// Generated by: npm run supabase:types
// Run this command after each migration to keep types in sync with the local schema.
// Do not edit manually — changes will be overwritten on the next type generation.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
